spring:
  application:
    name: newsSummury
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false


  ai:
    openai:
     api-key: ${OPENAI_API_KEY}
     chat:
       options:
         model: gpt-4



